### ISSUE TITLE
Blank runfiles from SBF shared scratch, /null can be removed

### ISSUE THREAD

**Issue by keiran-rowell-unsw** [Australian-Structural-Biology-Computing/old_proteinfold#11]
https://github.com/Australian-Structural-Biology-Computing/proteinfold/blob/8ce05982ff57ba3722c4e87093307b68f9923d43/null/pipeline_info/execution_trace_2024-07-29_14-54-51.txt#L1

**Comment by jscgh** [comment]
https://github.com/Australian-Structural-Biology-Computing/proteinfold/commit/3a13ab763b4d9ba9add54b319044e821c03212b6
